//Запрос данных
GET https://my-server-dz25.herokuapp.com/carsOwners


###
//Отправка вызывает изменения
POST https://my-server-dz25.herokuapp.com/carsOwners;
Content-Type: application/json


###
//PATCH используется для частичного изменения ресурса.
PATCH https://my-server-dz25.herokuapp.com/carsOwners/3
Content-Type: application/json
 
{
    "name": "Vasiliy Petrovich 1231",
    "phone": "+375293767082",
    "car": [
      {
        "id": 1,
        "brand": "2Lada",
        "carMileage": 222000,
        "registerSign": "7785AA-4",
        "replacementParts": [
          {
            "id": 1,
            "masterName": "Kshishtykov",
            "replacementMileage": 222000,
            "data": "07.07.2019",
            "work": "Еiming belt replacement",
            "priceWork": 10,
            "priceParts": 10
          }
        ],
        "futureWorkPlan": []
      }
    ]
  }

###
# DELETE удаляет указанный ресурс.
DELETE https://my-server-dz25.herokuapp.com/carsOwners/3 


###
//PUT заменяет все текущие представления ресурса данными запроса.
PUT https://my-server-dz25.herokuapp.com/carsOwners/3
Content-Type: application/json

{
  "id": 3,
  "name": "Vasiliy Petrovich",
  "phone": "+375293767082",
  "car": [
    {
      "id": 1,
      "brand": "2La231da",
      "carMileage": 222000,
      "registerSign": "7785AA-4",
      "replacementParts": [
        {
          "id": 1,
          "masterName": "Kshishtykov",
          "replacementMileage": 222000,
          "data": "07.07.2019",
          "work": "Еiming belt replacement",
          "priceWork": 10,
          "priceParts": 10
        }
      ],
      "futureWorkPlan": []
    }
  ]
}