//Запрос данных
GET https://firebasestorage.googleapis.com/v0/b/aliakseizhorau.appspot.com/o/ex.json?alt=media&token=a40e9995-b297-4165-a016-0d76a83390c7


###
//Отправка вызывает изменения
POST https://firebasestorage.googleapis.com/v0/b/aliakseizhorau.appspot.com/o/ex.json?alt=media&token=a40e9995-b297-4165-a016-0d76a83390c7;
Content-Type: application/json

{
    "name": "sample23 ds",
    "time": "Wed, 21 Oct 2015 18:27:50 GMTsfsefse"
},
{
    "name": "sample23 ds",
    "time": "Wed, 21 Oct 2015 18:27:50 GMTsfsefse"
},
{
    "name": "sample23 ds",
    "time": "Wed, 21 Oct 2015 18:27:50 GMTsfsefse"
}



###
//PATCH используется для частичного изменения ресурса.
PATCH  https://firebasestorage.googleapis.com/v0/b/aliakseizhorau.appspot.com/o/ex.json?alt=media&token=a40e9995-b297-4165-a016-0d76a83390c7;
Content-Type: application/json
 
  {
    "masterId": 1,
    "time": "13:12",
    "brand": "BMW",
    "phone": "+375291111111",
    "name": "Vasiliy Petrovich",
    "work": "Еiming belt replacement",
    "registerSign": "7785AA-4",
    "carMileage": 222000,
    "yearIssue": 2017,
    "priceWork": 10,
    "priceParts": 10
  }
 


###
# DELETE удаляет указанный ресурс.
DELETE https://my-server-dz25.herokuapp.com/carsOwners/3 


###
//PUT заменяет все текущие представления ресурса данными запроса.
PUT https://my-server-dz25.herokuapp.com/books/0
Content-Type: application/json

{
    "masterId": 1,
    "time": "13:12",
    "brand": "BMW",
    "phone": "+375291111111",
    "name": "Vasiliy Petrovich",
    "work": "Еiming belt replacement",
    "registerSign": "7785AA-4",
    "carMileage": 222000,
    "yearIssue": 2017,
    "priceWork": 10,
    "priceParts": 10
  }